# Generated by Django 3.2 on 2022-12-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20221204_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='slug',
        ),
    ]
