# Generated by Django 3.2 on 2022-12-07 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20221204_1601'),
        ('store', '0003_remove_reviewrating_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tên tác giả'),
        ),
        migrations.AlterField(
            model_name='detailinventory',
            name='amount',
            field=models.IntegerField(verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='detailinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Sách'),
        ),
        migrations.AlterField(
            model_name='detailinventory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ManyToManyField(to='store.Author', verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='category.category', verbose_name='Thể loại'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='photos/products', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày nhập'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_page',
            field=models.IntegerField(null=True, verbose_name='Số trang'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Giá '),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_import',
            field=models.IntegerField(verbose_name='Giá nhập'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tên sách'),
        ),
        migrations.AlterField(
            model_name='product',
            name='public_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.publiccompany', verbose_name='Nhà xuất bản'),
        ),
        migrations.AlterField(
            model_name='product',
            name='public_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày phát hành'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='saled',
            field=models.IntegerField(default=0, editable=False, verbose_name='Đã bán'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=20, null=True, verbose_name='Kích thước'),
        ),
        migrations.AlterField(
            model_name='publiccompany',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Đánh giá'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày bình luận'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Đã mua'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Sao'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
