# Generated by Django 3.2 on 2022-12-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20221207_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailinventory',
            options={'verbose_name': 'Chi tiết phiếu nhập', 'verbose_name_plural': 'Chi tiết phiếu nhập'},
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
