# Generated by Django 3.2 on 2022-10-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quanlity',
            new_name='quantity',
        ),
    ]
