# Generated by Django 3.2 on 2022-12-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_alter_cart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Chi tiết giỏ hàng', 'verbose_name_plural': 'Chi tiết giỏ hàng'},
        ),
    ]
