# Generated by Django 3.2 on 2022-12-04 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20221204_1601'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20221204_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Thanh toán', 'verbose_name_plural': 'Thanh toán'},
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='number_phone',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carts.cart', verbose_name='Giỏ hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(verbose_name='Ngày tạo đơn'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Mới'), ('Completed', 'Đã thanh toán'), ('Cancelled', 'Hủy đơn')], default='New', max_length=200, verbose_name='Tình trạng đơn hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(editable=False, verbose_name='Tổng giá'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày thanh toán'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order', verbose_name='Đơn hàng'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Tiền mặt'), ('CARD', 'Thẻ tín dụng')], default='CASH', max_length=200, verbose_name='Hình thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Người mua hàng'),
        ),
    ]
