# Generated by Django 3.2 on 2022-12-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20221204_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_phone',
            field=models.CharField(max_length=10),
        ),
    ]
